version: '2'

services:
  db:
    image: postgres:9.4

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    command: serve
    volumes:
      - ./:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/.credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.credentials
      - PROJECT_ID
